ControllerDemo/Models/Monkey.cs
using System;

namespace ControllerDemo.Models {
    public class Monkey {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ScientificName { get; set; }
        public bool Active { get; set; }
        public DateTime DateCreated { get; set; }
    }
}

ControllerDemo/Models/MonkeyHtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControllerDemo.Models {
    public class MonkeyHtml {
        public static string FridayHtml =
            "<html><body><h1>It's Friday!</h1><br /><iframe src=\"http://en.m.wikipedia.org/wiki/Friday_(Rebecca_Black_song)\" width=\"100%\" height=\"100%\" frameborder=\"none\"></iframe></body></html>";
    }
}

ControllerDemo/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ControllerDemo.Controllers {
    public class HomeController : Controller {
        // GET: /Home/
        public ActionResult Index() {
            return View();
        }
    }
}

ControllerDemo/Controllers/MonkeyController.cs
using System.Text;
using System.Web.Mvc;
using ControllerDemo.Models;

namespace ControllerDemo.Controllers {
    public class MonkeyController : Controller {
        #region ActionResult Examples

        // GET: /Monkey/
        /// <summary>Return Raw HTML</summary>
        public ActionResult Index() {
            StringBuilder sb = new StringBuilder();
            sb.Append("<html><head><title>Testing</title></head>");
            sb.Append("<body>");
            sb.Append("<h1>Raw Html</h1>");
            sb.Append("<div class=\"main\">The Body of the Page<br /><br />");
            sb.Append("<a href=\"" + Url.Action("Index", "Home") + "\">Home</a>");
            sb.Append("</div></body></html>");
            return Content(sb.ToString(), "text/html");
        }

        // GET: /Monkey/Get/5
        /// <summary>Return Raw JSON</summary>
        public ActionResult Get(int id) {
            return Json(
                new {
                    Id = id,
                    Name = "George",
                    ScientificName = "Simia Curiosa",
                    Active = "true",
                    DateCreated = "1343404556"
                },
                JsonRequestBehavior.AllowGet);
        }

        // GET: /Monkey/Add
        public ActionResult Add() {
            return View("Add");
        }

        // POST: /Monkey/Add
        [HttpPost]
        public ActionResult Add(FormCollection collection) {
            try {
                // Create the Monkey, redirect user to home
                return RedirectToAction("Index");
            } catch {
                return View();
            }
        }

        // GET: /Monkey/Download
        /// <summary>Return an Image</summary>
        public FileResult Download() {
            string filename = Url.Content("~/Content/monkey.jpg");
            return File(filename, "image/jpeg", "DownloadedMonkey.jpg");
        }

        #endregion

        #region Filter Examples
        [FridayFilter]
        public ActionResult OnlyOnFriday() {
            return Content(MonkeyHtml.FridayHtml);
        }

        public ActionResult NotTheDay(string name) {
            return Content("<html><body>Not " + name + " like, I thought it was...</body></html>");
        }

        [TuesdayFilter]
        public ActionResult OnlyOnTuesday() {
            return Content("<html><body>Not the day I thought it was...</body></html>");
        }
        #endregion

        #region Unimplemented Actions

        // GET: /Monkey/Edit/5
        [Authorize]
        public ActionResult Edit(int id) {
            return View();
        }

        // POST: /Monkey/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection) {
            try {
                // TODO: Add update logic here
                return RedirectToAction("Index");
            } catch {
                return View();
            }
        }

        // GET: /Monkey/Delete/5
        public ActionResult Delete(int id) {
            return View();
        }

        // POST: /Monkey/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            try {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            } catch {
                return View();
            }
        }

        #endregion
    }
}

ControllerDemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div style="margin:10px;">
    <h2>Index (Home Controller)</h2>
    <div> 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>

    <div style="margin:10px 0 0 0;">
        <h3>Action Results</h3>
        @Html.ActionLink("Index", "Index", "Monkey") (Monkey Controller)<br /><br />
        @Html.ActionLink("Add Monkey", "Add", "Monkey") (Show Create Monkey Form)<br /><br />
        @Html.ActionLink("Get Monkey", "Get", "Monkey", 
            new { id = 1 }, null) (Return Json for Monkey with Id of 1)<br /><br />
        @Html.ActionLink("Download a Monkey", "Download", "Monkey")<br /><br />

        <h3>Filters</h3>
        @Html.ActionLink("Only on Friday", "OnlyOnFriday", "Monkey")<br /><br />
        @Html.ActionLink("Only on Tuesday", "OnlyOnTuesday", "Monkey")
    </div>
</div>

ControllerDemo/Views/Monkey/Add.cshtml
@model ControllerDemo.Models.Monkey

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Monkey</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ScientificName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ScientificName)
            @Html.ValidationMessageFor(model => model.ScientificName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Active)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Active)
            @Html.ValidationMessageFor(model => model.Active)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreated)
            @Html.ValidationMessageFor(model => model.DateCreated)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ControllerDemo/Views/Monkey/Edit.cshtml
@model ControllerDemo.Models.Monkey

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Monkey</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.scientificName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.scientificName)
            @Html.ValidationMessageFor(model => model.scientificName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Active)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Active)
            @Html.ValidationMessageFor(model => model.Active)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreated)
            @Html.ValidationMessageFor(model => model.DateCreated)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ControllerDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>